version: '3'
services:
  cassandra-1:
    build: ../images/cassandra/
    depends_on:
      - cassandra-2
      - cassandra-3
    environment:
      CASSANDRA_BROADCAST_ADDRESS: cassandra-1
      CASSANDRA_CLUSTER_NAME: cassandra-cluster
      CASSANDRA_LISTEN_ADDRESS: cassandra-1
      CASSANDRA_RPC_ADDRESS: cassandra-1
      CASSANDRA_SEEDS: "cassandra-2,cassandra-3"
    hostname: cassandra-1
    volumes:
      - ../data/cassandra-1/cassandra/:/var/lib/cassandra/
      - ../logs/cassandra-1/cassandra/:/var/log/cassandra/
  cassandra-2:
    build: ../images/cassandra/
    depends_on:
      - cassandra-3
    environment:
      CASSANDRA_BROADCAST_ADDRESS: cassandra-2
      CASSANDRA_CLUSTER_NAME: cassandra-cluster
      CASSANDRA_LISTEN_ADDRESS: cassandra-2
      CASSANDRA_RPC_ADDRESS: cassandra-2
      CASSANDRA_SEEDS: "cassandra-3"
    hostname: cassandra-2
    volumes:
      - ../data/cassandra-2/cassandra/:/var/lib/cassandra/
      - ../logs/cassandra-2/cassandra/:/var/log/cassandra/
  cassandra-3:
    build: ../images/cassandra/
    environment:
      CASSANDRA_BROADCAST_ADDRESS: cassandra-3
      CASSANDRA_CLUSTER_NAME: cassandra-cluster
      CASSANDRA_RPC_ADDRESS: cassandra-3
      CASSANDRA_LISTEN_ADDRESS: cassandra-3
    hostname: cassandra-3
    volumes:
      - ../data/cassandra-3/cassandra/:/var/lib/cassandra/
      - ../logs/cassandra-3/cassandra/:/var/log/cassandra/
