version: '3'
services:
  postgres:
    build: ../images/postgres/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    expose:
      - 5432
    hostname: postgres
    ports:
      - "6432:5432"
    volumes:
      - ../data/postgres/postgres/:/var/lib/postgresql/data/
