version: '3'
services:
  jupyter:
    build: ../images/jupyter/
    hostname: jupyter
    ports:
      - "9999:8888"
    volumes:
      - ../../notebooks/jupyter/:/home/jovyan/
      - ../../data/:/data/
